# YAML for global parameters used in majority of code (loaded by default)

#### GUIDE ####
# SAMPLING - list - Sampling Rate in z, x, y
# IGNORE_SAMPLERS - list - list of samplers to ignore (artefacts or missed
#                          annotations that might cause problems)

# SAMPLER - Parameters for Sampling
#    DISABLE_LABELS - bool - If True, do not sample cells independently
#    SILVER_TRUTH - bool - If True, use silver truth labels for sampling (not recommended)

#    MIN_DIST, MAX_DIST - float - Minimum internal, Maximum external distance to sample
#    DX - float - Bin size for distances (in mu, should be > 2x X-Y SAMPLING rate). 

# NOTE: BIN EDGE MUST LAND ON 0 (abs(min_dist) % DX == 0)
###############

SAMPLING: [1.0, 0.126, 0.126]
IGNORE_SAMPLERS: []

SAMPLER:
    DISABLE_LABELS: False
    NORMALISE: False
    SILVER_TRUTH: False
    MIN_DIST: -5
    MAX_DIST: 5
    DX: .252
    SKIP: 5